# Default values for invoiceninja.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: directus/directus
  tag: v9.0.0-rc.82
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

strategyType: "Recreate"

general:
  port: 8055
  public_url: '/'
  log_level: 'info'
  log_style: 'pretty'

security:
  admin_email: ''
  admin_password: ''
  key: ''
  secret: ''
  access_token_ttl: '15m'
  refresh_token_ttl: '7d'
  refresh_token_cookie_secure: false
  refresh_token_cookie_same_site: lax

database:
  client: 'postgres'
  host: ''
  port: ''
  database: ''
  username: ''
  password: ''
  filename: ''
  sslmode: ''

cors:
  enabled: true
  methods: 'GET,POST,PATCH,DELETE'
  allowed_headers: 'Content-Type,Authorization'
  exposed_headers: 'Content-Range'
  credentials: true
  max_age: 18000

rate_limiter:
  enabled: false
  points: 50
  duration: 1
  store: memory
  redis: ''
  redis_host: ''
  redis_port: ''
  redis_password: ''
  redis_db: '0'
  memcache: ''

cache:
  enabled: false
  ttl: '30m'
  namespace: 'directus-cache'
  store: 'memory'
  redis: ''
  redis_host: ''
  redis_port: ''
  redis_password: ''
  redis_db: ''
  memcache: ''

storage:
  locations: 's3'
  driver: s3
  key: ''
  secret: ''
  endpoint: ''
  bucket: ''
  region: ''
  public_url: ''

email:
  from: ''
  transport: 'smtp'
  sendmail_new_line: ''
  sendmail_path: ''
  smtp_host: ''
  smtp_port: ''
  smtp_user: ''
  smtp_password: ''
  smtp_pool: 'false'
  smtp_secure: 'false'

# Define config map for extensions/hooks
webhooks_config_map:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  paths:
    - /
  hosts: []
  tls:
    - secretName: crawless-directus-tls
      hosts: []

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations:
  fluentbit.io/exclude: "true"
