apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "directus-next.fullname" . }}-envs
  labels:
    app.kubernetes.io/name: {{ include "directus-next.name" . }}
    helm.sh/chart: {{ include "directus-next.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  PORT: "{{ .Values.general.port }}"
  PUBLIC_URL: "{{ .Values.general.public_url }}"
  LOG_LEVEL: "{{ .Values.general.log_level }}"
  LOG_STYLE: "{{ .Values.general.log_style }}"
  ACCESS_TOKEN_TTL: "{{ .Values.security.access_token_ttl }}"
  REFRESH_TOKEN_TTL: "{{ .Values.security.refresh_token_ttl }}"
  REFRESH_TOKEN_COOKIE_SECURE: "{{ .Values.security.refresh_token_cookie_secure }}"
  DIRECTUS_ADMIN_EMAIL: "{{ .Values.security.admin_email }}"
  REFRESH_TOKEN_COOKIE_SAME_SITE: "{{ .Values.security.refresh_token_cookie_same_site }}"
  DB_CLIENT: "{{ .Values.database.client }}"
  DB_HOST: "{{ .Values.database.host }}"
  DB_PORT: "{{ .Values.database.port }}"
  DB_DATABASE: "{{ .Values.database.database }}"
  DB_USER: "{{ .Values.database.username }}"
  PGSSLMODE: "{{ .Values.database.sslmode }}"
  DB_FILENAME: "{{ .Values.database.filename }}"
  CORS_ENABLED: "{{ .Values.cors.enabled }}"
  CORS_METHODS: "{{ .Values.cors.methods }}"
  CORS_ALLOWED_HEADERS: "{{ .Values.cors.allowed_headers }}"
  CORS_EXPOSED_HEADERS: "{{ .Values.cors.exposed_headers }}"
  CORS_CREDENTIALS: "{{ .Values.cors.credentials }}"
  CORS_MAX_AGE: "{{ .Values.cors.max_age }}"
  RATE_LIMITER_ENABLED: "{{ .Values.rate_limiter.enabled }}"
  RATE_LIMITER_POINTS: "{{ .Values.rate_limiter.points }}"
  RATE_LIMITER_DURATION: "{{ .Values.rate_limiter.duration }}"
  RATE_LIMITER_STORE: "{{ .Values.rate_limiter.store }}"
  RATE_LIMITER_REDIS: "{{ .Values.rate_limiter.redis }}"
  RATE_LIMITER_REDIS_HOST: "{{ .Values.rate_limiter.redis_host }}"
  RATE_LIMITER_REDIS_PORT: "{{ .Values.rate_limiter.redis_port }}"
  RATE_LIMITER_REDIS_PASSWORD: "{{ .Values.rate_limiter.redis_password }}"
  RATE_LIMITER_REDIS_DB: "{{ .Values.rate_limiter.redis_db }}"
  RATE_LIMITER_MEMCACHE: "{{ .Values.rate_limiter.memcache }}"
  STORAGE_LOCATIONS: "{{ .Values.storage.locations }}"
  STORAGE_S3_DRIVER: "{{ .Values.storage.driver }}"
  STORAGE_S3_PUBLIC_URL: "{{ .Values.storage.public_url }}"
  STORAGE_S3_KEY: "{{ .Values.storage.key }}"
  STORAGE_S3_SECRET: "{{ .Values.storage.secret }}"
  STORAGE_S3_ENDPOINT: "{{ .Values.storage.endpoint }}"
  STORAGE_S3_BUCKET : "{{ .Values.storage.bucket }}"
  STORAGE_S3_REGION : "{{ .Values.storage.region }}"
  EMAIL_FROM : "{{ .Values.email.from }}"
  EMAIL_TRANSPORT : "{{ .Values.email.transport }}"
  EMAIL_SENDMAIL_NEW_LINE : "{{ .Values.email.sendmail_new_line }}"
  EMAIL_SENDMAIL_PATH : "{{ .Values.email.sendmail_path }}"
  EMAIL_SMTP_HOST : "{{ .Values.email.smtp_host }}"
  EMAIL_SMTP_PORT : "{{ .Values.email.smtp_port }}"
  EMAIL_SMTP_USER : "{{ .Values.email.smtp_user }}"
  EMAIL_SMTP_PASSWORD : "{{ .Values.email.smtp_password }}"
  EMAIL_SMTP_POOL : "{{ .Values.email.smtp_pool }}"
  EMAIL_SMTP_SECURE : "{{ .Values.email.smtp_secure }}"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
