apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus-next.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "directus-next.name" . }}
    helm.sh/chart: {{ include "directus-next.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: "{{ .Values.database.password | b64enc }}"
  KEY: "{{ .Values.security.key | b64enc }}"
  SECRET: "{{ .Values.security.secret | b64enc }}"
  DIRECTUS_ADMIN_PASSWORD: "{{ .Values.security.admin_password | b64enc }}"
